package io.serena.javarefactor.project;

import java.nio.file.Path;
import java.util.List;

/**
 * Centralized generated-source / Lombok editability policy for V2 planning.
 *
 * <p>The <em>authority</em> for whether a file is a non-editable generated target is the build model's extracted
 * {@linkplain JavaProjectModel#generatedSourceRoots() generated source roots} (Maven/Gradle-derived, including
 * annotation-processor output directories that may live outside a conventional {@code /generated/} path). A file under
 * such a root is a non-editable target regardless of how its path or contents are named.
 *
 * <p>The path-substring and source-text-substring checks below are retained only as a <em>fallback</em> signal, used
 * when the build model does not (yet) cover a file — e.g. a conventionally-discovered project with no build tool, or a
 * hand-marked {@code @Generated} file outside any extracted root. They are deliberately <em>not</em> the sole gate: the
 * build model takes precedence, so a generated root reported by the build is honoured even when its path looks ordinary,
 * and an ordinary file is not refused merely because its path happens to contain {@code generated}.
 *
 * <p>This type is intentionally stateless and side-effect free so it can be unit-tested directly and reused from both
 * the protocol-level pre-dispatch gate ({@code Main}) and the planner-level editability checks.
 */
public final class GeneratedSourcePolicy {

    private GeneratedSourcePolicy() {
    }

    /**
     * Whether {@code file} lies under any build-model generated source root. This is the authoritative signal: a match
     * means the file is generated according to the resolved build, and an edit to it must be refused as a non-editable
     * target.
     *
     * @param generatedRoots build-model generated source roots (need not be pre-normalized)
     * @param file           candidate file (need not be pre-normalized)
     */
    public static boolean isUnderGeneratedRoot(List<Path> generatedRoots, Path file) {
        if (generatedRoots == null || generatedRoots.isEmpty() || file == null) {
            return false;
        }
        Path normalizedFile = file.toAbsolutePath().normalize();
        for (Path root : generatedRoots) {
            if (root == null) {
                continue;
            }
            if (normalizedFile.startsWith(root.toAbsolutePath().normalize())) {
                return true;
            }
        }
        return false;
    }

    /**
     * Fallback path-naming heuristic for generated output that the build model did not surface. Matches the conventional
     * Gradle/Maven generated-output layouts ({@code build/generated/...}, {@code target/generated-...}) and any path with
     * a {@code /generated/} segment.
     */
    public static boolean matchesGeneratedPathHeuristic(String relativePath) {
        if (relativePath == null) {
            return false;
        }
        String normalized = relativePath.replace('\\', '/');
        return normalized.contains("/generated/")
                || normalized.startsWith("generated/")
                || normalized.contains("/build/generated/")
                || normalized.contains("/target/generated-");
    }

    /**
     * Fallback source-text heuristic for a file carrying an {@code @Generated} marker (or an {@code // <auto-generated}
     * banner) when it is not covered by a build-model generated root.
     */
    public static boolean matchesGeneratedSourceText(String source) {
        if (source == null) {
            return false;
        }
        return source.contains("@Generated")
                || source.contains("javax.annotation.Generated")
                || source.contains("jakarta.annotation.Generated")
                || source.contains("// <auto-generated");
    }

    /**
     * Fallback source-text heuristic for Lombok-managed sources: Lombok synthesizes API (getters/setters/builders) at
     * compile time, so a file that opts into Lombok carries declarations with no editable source and is treated as not
     * source-editable unless the caller explicitly opts in.
     */
    public static boolean matchesLombokSourceText(String source) {
        if (source == null) {
            return false;
        }
        return source.contains("import lombok.")
                || source.contains("@Getter")
                || source.contains("@Setter")
                || source.contains("@Data")
                || source.contains("@Value")
                || source.contains("@Builder");
    }
}
