package io.serena.javarefactor.project;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit coverage for {@link GeneratedSourcePolicy}: the build model's generated source roots are the authoritative
 * non-editable-target signal, while the path-/source-text checks are fallback-only. These assertions pin the exact
 * behaviour the protocol- and planner-level editability gates rely on (build-model match wins; an ordinary path is not
 * refused; a heuristic match only fires when the build model is silent).
 */
class GeneratedSourcePolicyTest {

    @Test
    void fileUnderBuildModelGeneratedRootIsAuthoritativeMatch(@TempDir Path root) {
        // The generated root path deliberately does NOT contain "/generated/", so only the build-model authority (not a
        // path heuristic) can classify a file beneath it — mirroring an annotation-processor output dir like build/apout.
        Path generatedRoot = root.resolve("build/apout");
        Path generatedFile = generatedRoot.resolve("example/gen/Gen.java");
        assertTrue(GeneratedSourcePolicy.isUnderGeneratedRoot(List.of(generatedRoot), generatedFile));
        assertFalse(GeneratedSourcePolicy.matchesGeneratedPathHeuristic("build/apout/example/gen/Gen.java"),
                "build/apout must not match the path heuristic — only the build model knows it is generated");
    }

    @Test
    void fileOutsideEveryGeneratedRootIsNotAMatch(@TempDir Path root) {
        Path generatedRoot = root.resolve("src/generated/java");
        Path ordinaryFile = root.resolve("src/main/java/demo/App.java");
        assertFalse(GeneratedSourcePolicy.isUnderGeneratedRoot(List.of(generatedRoot), ordinaryFile));
        assertFalse(GeneratedSourcePolicy.isUnderGeneratedRoot(List.of(), ordinaryFile));
    }

    @Test
    void pathHeuristicMatchesConventionalGeneratedLayouts() {
        assertTrue(GeneratedSourcePolicy.matchesGeneratedPathHeuristic("generated/Gen.java"));
        assertTrue(GeneratedSourcePolicy.matchesGeneratedPathHeuristic("src/generated/java/demo/Gen.java"));
        assertTrue(GeneratedSourcePolicy.matchesGeneratedPathHeuristic("module/build/generated/sources/Gen.java"));
        assertTrue(GeneratedSourcePolicy.matchesGeneratedPathHeuristic("module/target/generated-sources/Gen.java"));
        assertFalse(GeneratedSourcePolicy.matchesGeneratedPathHeuristic("src/main/java/demo/Generated.java"),
                "a type named Generated in an ordinary source dir must not be refused by path");
    }

    @Test
    void sourceTextHeuristicsDetectGeneratedAndLombokMarkers() {
        assertTrue(GeneratedSourcePolicy.matchesGeneratedSourceText("import javax.annotation.Generated;\n@Generated class X {}"));
        assertTrue(GeneratedSourcePolicy.matchesGeneratedSourceText("// <auto-generated/>\nclass X {}"));
        assertFalse(GeneratedSourcePolicy.matchesGeneratedSourceText("package demo; class X {}"));

        assertTrue(GeneratedSourcePolicy.matchesLombokSourceText("import lombok.Data;\n@Data class X {}"));
        assertTrue(GeneratedSourcePolicy.matchesLombokSourceText("@Builder class X {}"));
        assertFalse(GeneratedSourcePolicy.matchesLombokSourceText("package demo; class X { int data; }"));
    }
}
